### ISSUE TITLE
did not work with XBEE PRO S3B... is there some update?

### ISSUE THREAD

**Issue by ingebernal** [niolabs/python-xbee#58]
My programm works very well with s2b but with pro s3b didn't. The modules are working with the xbee software very well 2milles of range. 

Thanks in advance.

**Comment by jamesleesaunders** [comment]
Hi @ingerbernal We would need more information. Error messages? What does not work? How do you expect it to work.
All the best.

**Comment by ingebernal** [comment]
I recieve any information from the shield in the terminal screen. When I change it with the S2B it works very well. 
Thanks
