### ISSUE TITLE
Xbee satisfies the requirement on install

### ISSUE THREAD

**Issue by Bryan-Tam** [niolabs/python-xbee#71]
I am trying to install python-xbee and it is throwing the error of "could not find a version that satisfies the requirement xbee...". When I check the pip list, XBee 2.3.2 appears in that list, however the module is not found when imported in python. I'm not sure what else to do to fix the problem as other similar issues were not totally resolved. As of right now there seems to be no other means to read an API XBee frame.

**Comment by mattdodge** [comment]
It sounds like there's a discrepancy between your `pip` and `python` executables.

Rather than `pip list` what does `python -m pip list` show you? You can try installing with `python -m pip install xbee` too to see if that resolves it.

**Comment by mattdodge** [comment]
Going to call this one done - if it's still an issue or the previous suggestions don't work let me know and I'll re-open

**Comment by Bryan-Tam** [comment]
Hi Matt, I had to reinstall python and pip from the beginning to get it working again.
